# permissions for end users to view configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: malloryh-kb-operator
    app.kubernetes.io/managed-by: kustomize
  name: config-configuration-viewer-role
rules:
- apiGroups:
  - config.core.malloryh-1210.io
  resources:
  - configurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.core.malloryh-1210.io
  resources:
  - configurations/status
  verbs:
  - get
